name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Assign Tag Number to RELEASE_VERSION environment variable
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Publish libtesseract
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.RELEASE_VERSION }}
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}