name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Assign Tag Number to RELEASE_VERSION environment variable
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: Publish libtesseract
      run: go run publish.go -version $RELEASE_VERSION -bintray-key ${{ secrets.BINTRAY_KEY }} -publish
      working-directory: publish